"""First migration

Revision ID: 3c5ae4533176
Revises:
Create Date: 2026-01-03 15:28:16.950560

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = "3c5ae4533176"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # MUST come first
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table(
        "pdfs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("minio_key", sa.String(length=500), nullable=False),
        sa.Column("file_size", sa.BigInteger(), nullable=False),
        sa.Column("total_pages", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pdfs")),
    )
    op.create_table(
        "chat_messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("pdf_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("retrieved_chunk_ids", sa.ARRAY(sa.UUID()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["pdf_id"], ["pdfs.id"], name=op.f("fk_chat_messages_pdf_id_pdfs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_messages")),
    )
    op.create_index(
        "idx_chat_messages_pdf_id_created_at",
        "chat_messages",
        ["pdf_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "pdf_chunks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("pdf_id", sa.UUID(), nullable=False),
        sa.Column("chunk_text", sa.Text(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=True),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("embedding", Vector(dim=1536), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["pdf_id"], ["pdfs.id"], name=op.f("fk_pdf_chunks_pdf_id_pdfs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pdf_chunks")),
    )
    op.create_index("idx_pdf_chunks_pdf_id", "pdf_chunks", ["pdf_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_pdf_chunks_pdf_id", table_name="pdf_chunks")
    op.drop_table("pdf_chunks")
    op.drop_index("idx_chat_messages_pdf_id_created_at", table_name="chat_messages")
    op.drop_table("chat_messages")
    op.drop_table("pdfs")
    # ### end Alembic commands ###
